# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  schedule:
    - cron: 0 0 * * *

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: npm install
      run: npm install
    - name: build website
      run: npm run build --if-present
    - name: setup aliyun oss
      uses: manyuanrong/setup-ossutil@v2.0
      with:
        endpoint: oss-cn-beijing.aliyuncs.com
        access-key-id: ${{secrets.ALIYUN_ACCESS_ID}}
        access-key-secret: ${{secrets.ALIYUN_ACCESS_SECRET}}
    - name: clean oss
      run: ossutil rm oss://yongheonline/ -r
    - name: Deply To OSS
      run: ossutil cp public oss://yongheonline/ -rf
